### ISSUE TITLE
networkActiveModuleType parameter and pygame.display.flip() error [Ubuntu 22.04 LTS]

### ISSUE THREAD

**Issue by prateekbhaisora** [carlanet/carlanetpp#2]
Hi

I was trying to run the co-simulation between Carla and OMNetpp using carlanet and I am trying to run to run the example car_light_control. 
First, I started the Carla Server and ran the pycarlanet client by executing the following commands:

```sh
./CarlaUE4.sh -carla-server -carla-server-ip=10.194.42.240 -carla-server-port=2000

python3.8 -m example.car_light_control.main 10.194.42.240 2000
```

After building and running the simulation via Omnet++ IDE, it expects an input as below:

![Screenshot from 2024-05-19 12-49-45](https://github.com/carlanet/carlanetpp/assets/43443861/a9ea69c6-053e-4a10-8a6e-3a7a86aa7776)

Regardless of what I enter as an input. The simulation fails with the following error message in the pycarlanet terminal:

![Screenshot from 2024-05-19 12-51-52](https://github.com/carlanet/carlanetpp/assets/43443861/b73210ca-4fe4-4c87-8f88-6aacb87506ad)
![Screenshot from 2024-05-19 12-53-12](https://github.com/carlanet/carlanetpp/assets/43443861/4393f9d4-b5d7-41af-a0e6-204b9ecab566)

Omnet++ IDE Shows this:

![Screenshot from 2024-05-19 12-52-20](https://github.com/carlanet/carlanetpp/assets/43443861/2208a28a-0cf8-4ada-89f0-19e1f82006da)

Please help me figure out the issue.

**Comment by prateekbhaisora** [comment]
Update: The display.flip() issue got resolved automatically after I downgraded my pygame version from 3.2.0 to 2.0.0. The parameter value was supposed to be left empty.

**Comment by jaivra** [comment]
Hi,

Have you been able to run the car_light_control example correctly?

**Comment by prateekbhaisora** [comment]
> Hi,
> 
> 
> 
> Have you been able to run the car_light_control example correctly?

Yes I was able to run it correctly. Thanks for asking :)
